### ISSUE TITLE
Build new image for kube 1.18?

### ISSUE THREAD

**Issue by jandubois** [f0rmiga/opensuse-minikube-image#20]
I tried to just rebuild the current image by cloning this repo and running `make build-in-docker` inside it (on an openSUSE Leap 15 host). It failed with:

```
[ ERROR   ]: 01:43:42 | KiwiCommandError: losetup: stderr: losetup: /tmp/tmp4_tddwq8: failed to set up loop device: No such file or directory
, stdout: (no output on stdout)
```

Any idea how to fix that?

Or alternatively, could you build a new image that supports kube 1.18? The current image throws an error:

```
[preflight] Running pre-flight checks

stderr:
W0717 00:09:50.876664    5455 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR FileExisting-conntrack]: conntrack not found in system path
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
```

I'm hoping that adding `conntrack-tools` to the list of packages would fix the error, but obviously haven't tested it yet. The warnings can probably be ignored (or at least looked into once the error has been addressed).

Anyways, a hint on how I could build a new image myself would be excellent (so I could investigate any other issues as they might come up), but I'll take a working image for k8s 1.18 as well. 😄

**Comment by jandubois** [comment]
The problem turned out to be that a parent of the current directory was a symlink. That seems to have interfered with the ability to write to a mounted subdirectory from inside the build container.

I'll leave this issue open because we still need a released image supporting kube 1.18.

**Comment by f0rmiga** [comment]
https://github.com/f0rmiga/opensuse-minikube-image/pull/22 includes support for k8s 1.18. I'll release a new version in a second.

**Comment by f0rmiga** [comment]
Released in https://github.com/f0rmiga/opensuse-minikube-image/releases/tag/v0.1.8.
